server:
  port: 0

spring:
  application:
    name: PROMOTION-SERVICE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  jackson:
    deserialization:
      fail-on-unknown-properties: true

feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: false
  hc5:
    enabled: true

logging:
  level:
    root: info
    by.javaguru.jdmik11.promotionservice: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakerevents,retry
  health:
    circuitbreakerevents:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      promotion-service-circuit-breaker:
        record-exceptions:
          - by.javaguru.jdmik11.promotionservice.api.exception.SecurityServiceError
          - by.javaguru.jdmik11.promotionservice.api.exception.AccountingServiceError
          - by.javaguru.jdmik11.promotionservice.api.exception.ProfilerServiceError
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        sliding-window-type: count_based
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 3
    circuit-breaker-aspect-order: 1
  retry:
    instances:
      promotion-service-retry:
        retry-exceptions:
          - by.javaguru.jdmik11.promotionservice.api.exception.SecurityServiceError
          - by.javaguru.jdmik11.promotionservice.api.exception.AccountingServiceError
          - by.javaguru.jdmik11.promotionservice.api.exception.ProfilerServiceError
        max-attempts: 5
        wait-duration:
          seconds: 5
    retry-aspect-order: 2